version: "2"

services:
  mongo:
    image: mongo:4.4.1
    restart: always
    ports:
      - 27017:27017

  api:
    image: faloker/purify-api-test
    restart: always
    depends_on:
      - mongo
    env_file:
      - ./api/.env.dev

  nginx:
    image: faloker/purify-nginx-test
    restart: always
    depends_on:
      - api
    ports:
      - 8080:8080
