version: "2"

services:
  mongo:
    image: mongo:4.4.1
    restart: always

  api:
    image: "faloker/purify-api-test:${GITHUB_RUN_ID}"
    restart: always
    depends_on:
      - mongo
    env_file:
      - ./api/.env.dev

  nginx:
    image: "faloker/purify-nginx-test:${GITHUB_RUN_ID}"
    restart: always
    depends_on:
      - api
    ports:
      - 8080:8080
