version: "2"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_db:/data/db

  app:
    # build: .
    image: faloker/purify
    restart: always
    depends_on:
      - "mongo"
    ports:
      - "8080:3000"
    environment:
      NODE_ENV: production
      MONGO_USERNAME: root
      MONGO_PASSWORD: example

volumes:
  mongo_db: {}    