version: "2"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  api:
    build:
      context: .
      dockerfile: api.dockerfile
    restart: always
    depends_on:
      - mongo

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
      args:
        env: dev
    restart: always
    depends_on:
      - api
    ports:
      - 8080:8080
