version: "2"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_db:/data/db

  api:
    image: faloker/purify-api
    restart: always
    depends_on:
      - mongo
    environment:
      NODE_ENV: prod

  nginx:
    image: faloker/purify-nginx
    restart: always
    volumes:
      - /path/to/cert:/etc/nginx/ssl/cert
      - /path/to/key:/etc/nginx/ssl/key
    depends_on:
      - api
    ports:
      - 443:443
      - 80:80

volumes:
  mongo_db: {}
