name: E2E on Chrome
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Run tests
      uses: cypress-io/github-action@v2
      with:
        build: npm run start:test
        browser: chrome
        record: true
        group: 'Chrome'
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

