name: E2E on Chrome
on: [pull_request]
jobs:
  build-api-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: '${{ secrets.DOCKER_HUB_USERNAME }}'
          password: '${{ secrets.DOCKER_HUB_KEY }}'
          image_name: faloker/purify-api-test
          dockerfile: api.dockerfile

  build-nginx-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: '${{ secrets.DOCKER_HUB_USERNAME }}'
          password: '${{ secrets.DOCKER_HUB_KEY }}'
          image_name: faloker/purify-nginx-test
          dockerfile: nginx.dockerfile
          build_extra_args: "--build-arg=env=dev"

  chrome-run:
    needs: ['build-api-image', 'build-nginx-image']
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8]
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run start:ci
          browser: chrome
          record: true
          parallel: true
          group: 'Chrome'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  firefox-run:
    needs: ['build-api-image', 'build-nginx-image']
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.14.1-chrome83-ff77
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8]
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run start:ci
          browser: firefox
          record: true
          parallel: true
          group: 'Firefox'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
