name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install root dependencies
        uses: npm i
      - name: Start server with docker-compose
        run:  npm start
      - name: Execute tests
        run:  npm run cy:run

